// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8UJY_NrQnLnjhQDOKq_DgiA299VYCFgM',
    appId: '1:132972912332:web:3e55e90187dd29ebba2c69',
    messagingSenderId: '132972912332',
    projectId: 'heybridge-5f6ed',
    authDomain: 'heybridge-5f6ed.firebaseapp.com',
    storageBucket: 'heybridge-5f6ed.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8bN6UteEO5gN6zFSX47AxxBAd_6YA2LU',
    appId: '1:132972912332:android:33a06d3123139f17ba2c69',
    messagingSenderId: '132972912332',
    projectId: 'heybridge-5f6ed',
    storageBucket: 'heybridge-5f6ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy_agPKCjjf2MvjN23q3RrwScQxb3tte8',
    appId: '1:132972912332:ios:72b79a90b49c91d0ba2c69',
    messagingSenderId: '132972912332',
    projectId: 'heybridge-5f6ed',
    storageBucket: 'heybridge-5f6ed.firebasestorage.app',
    iosBundleId: 'com.example.heybridge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy_agPKCjjf2MvjN23q3RrwScQxb3tte8',
    appId: '1:132972912332:ios:72b79a90b49c91d0ba2c69',
    messagingSenderId: '132972912332',
    projectId: 'heybridge-5f6ed',
    storageBucket: 'heybridge-5f6ed.firebasestorage.app',
    iosBundleId: 'com.example.heybridge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8UJY_NrQnLnjhQDOKq_DgiA299VYCFgM',
    appId: '1:132972912332:web:997f6b8b92e9237fba2c69',
    messagingSenderId: '132972912332',
    projectId: 'heybridge-5f6ed',
    authDomain: 'heybridge-5f6ed.firebaseapp.com',
    storageBucket: 'heybridge-5f6ed.firebasestorage.app',
  );
}
